import SwiftUI
import SwiftJsonUI
import Combine

struct TextStylingTestGeneratedView: View {
    @EnvironmentObject var viewModel: TextStylingTestViewModel
    @StateObject private var dynamicViewModel = DynamicViewModel(jsonName: "text_styling_test")
    
    var body: some View {
        if ViewSwitcher.isDynamicMode {
            DynamicView(jsonName: "text_styling_test", viewId: "text_styling_test_view", data: viewModel.data.toDictionary(viewModel: viewModel))
                .environmentObject(dynamicViewModel)
        } else {
            // Generated SwiftUI code from text_styling_test.json
            // This will be updated when you run 'sjui build'
            // >>> GENERATED_CODE_START
            AdvancedKeyboardAvoidingScrollView(.vertical, showsIndicators: true) {
                VStack(alignment: .leading, spacing: 0) {
                    Text("\(viewModel.data.title)")
                        .font(.system(size: 24))
                        .foregroundColor(Color(red: 0.0, green: 0.0, blue: 0.0))
                        .padding(.top, 20)
                    Text("Font Sizes")
                        .font(.system(size: 18))
                        .foregroundColor(Color(red: 0.2, green: 0.2, blue: 0.2))
                        .fontWeight(.bold)
                        .padding(.top, 20)
                    Text("fontSize: 12")
                        .font(.system(size: 12))
                        .padding(.top, 10)
                    Text("fontSize: 16")
                        .font(.system(size: 16))
                        .padding(.top, 5)
                    Text("fontSize: 20")
                        .font(.system(size: 20))
                        .padding(.top, 5)
                    Text("fontSize: 24")
                        .font(.system(size: 24))
                        .padding(.top, 5)
                    Text("Font Styles")
                        .font(.system(size: 18))
                        .foregroundColor(Color(red: 0.2, green: 0.2, blue: 0.2))
                        .fontWeight(.bold)
                        .padding(.top, 20)
                    Text("Bold Text")
                        .font(.system(size: 16))
                        .fontWeight(.bold)
                        .padding(.top, 10)
                    Text("Underlined Text")
                        .font(.system(size: 16))
                        .underline()
                        .padding(.top, 10)
                    Text("Text Alignment")
                        .font(.system(size: 18))
                        .foregroundColor(Color(red: 0.2, green: 0.2, blue: 0.2))
                        .fontWeight(.bold)
                        .padding(.top, 20)
                    Text("Left Aligned (default)")
                        .font(.system(size: 16))
                        .multilineTextAlignment(.leading)
                        .frame(maxWidth: .infinity)
                        .background(Color(red: 0.8784313725490196, green: 0.8784313725490196, blue: 0.8784313725490196))
                        .padding(.top, 10)
                        .padding(5)
                    Text("Center Aligned")
                        .font(.system(size: 16))
                        .multilineTextAlignment(.center)
                        .frame(maxWidth: .infinity)
                        .background(Color(red: 0.8784313725490196, green: 0.8784313725490196, blue: 0.8784313725490196))
                        .padding(.top, 10)
                        .padding(5)
                    Text("Right Aligned")
                        .font(.system(size: 16))
                        .multilineTextAlignment(.trailing)
                        .frame(maxWidth: .infinity)
                        .background(Color(red: 0.8784313725490196, green: 0.8784313725490196, blue: 0.8784313725490196))
                        .padding(.top, 10)
                        .padding(5)
                    Text("Line Spacing Test")
                        .font(.system(size: 18))
                        .foregroundColor(Color(red: 0.2, green: 0.2, blue: 0.2))
                        .fontWeight(.bold)
                        .padding(.top, 20)
                    Text("This is a multi-line text with lineSpacing: 5 to demonstrate line spacing")
                        .font(.system(size: 14))
                        .lineSpacing(5.0)
                        .background(Color(red: 0.9411764705882353, green: 0.9411764705882353, blue: 0.9411764705882353))
                        .padding(.top, 10)
                        .padding(10)
                    Text("This is another multi-line text with lineSpacing: 10 to demonstrate line spacing (line breaks work with proper spacing)")
                        .font(.system(size: 14))
                        .lineSpacing(10.0)
                        .background(Color(red: 0.9411764705882353, green: 0.9411764705882353, blue: 0.9411764705882353))
                        .padding(.top, 10)
                        .padding(10)
                    Text("Font Colors")
                        .font(.system(size: 18))
                        .foregroundColor(Color(red: 0.2, green: 0.2, blue: 0.2))
                        .fontWeight(.bold)
                        .padding(.top, 20)
                    Text("Red Text")
                        .font(.system(size: 16))
                        .foregroundColor(Color(red: 1.0, green: 0.0, blue: 0.0))
                        .padding(.top, 10)
                    Text("Green Text")
                        .font(.system(size: 16))
                        .foregroundColor(Color(red: 0.0, green: 1.0, blue: 0.0))
                        .padding(.top, 5)
                    Text("Blue Text")
                        .font(.system(size: 16))
                        .foregroundColor(Color(red: 0.0, green: 0.0, blue: 1.0))
                        .padding(.top, 5)
                }
                    .frame(maxWidth: .infinity)
            }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Color(red: 0.9725490196078431, green: 0.9725490196078431, blue: 0.9725490196078431))
            // >>> GENERATED_CODE_END
        }
    }
}
